name: delete-ingress-certmanager
on: workflow_dispatch

env:
  SECRET_NAME: app-tls
  SECRET_NAMESPACE: default

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:

      - name: Delete Cert-manager
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: ${{ secrets.MASTER_NODE_USERNAME }}
          password: ${{ secrets.MASTER_NODE_PASSWORD }}
          script: |
            helm uninstall cert-manager


      - name: Delete Ingress
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: ${{ secrets.MASTER_NODE_USERNAME }}
          password: ${{ secrets.MASTER_NODE_PASSWORD }}
          script: |
            helm uninstall ingress
            

      - name: Delete Secret Tls
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: ${{ secrets.MASTER_NODE_USERNAME }}
          password: ${{ secrets.MASTER_NODE_PASSWORD }}
          envs: SECRET_NAME, SECRET_NAMESPACE
          script: |
            k delete secret app-tls -n default