name: Setting-postgresql
#starting only by manual command
on: workflow_dispatch

env:
  MESSAGE: "Hello, World!"
  BD_PASSWORD: ${{secrets.BD_PASSWORD}}
  BD_USER: ${{secrets.BD_USER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Up Postgresql
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DB_NODE_HOST }}
          username: ${{ secrets.DB_NODE_USERNAME }}
          password: ${{ secrets.DB_NODE_PASSWORD }}
          envs: MESSAGE, BD_PASSWORD, BD_USER
          script: |
            docker run \
            --name ze_db \
            -e POSTGRES_PASSWORD=$(echo $BD_PASSWORD) \
            -e POSTGRES_USER=$(echo $BD_USER) \
            -p 5432:5432 \
            -v ze_db:/var/lib/postgresql/data/ \
            -d \
            postgres:14.3-alpine
            
            echo $(echo $BD_PASSWORD)
            echo $(echo $BD_USER)