name: Setting-postgresql
#starting only by manual command
on: workflow_dispatch

env:
  MESSAGE: "Hello, World!"
  BD_PASSWORD: ${{secrets.BD_PASSWORD}}
  BD_USER: ${{secrets.BD_USER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Up Postgresql
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DB_NODE_HOST }}
          username: ${{ secrets.DB_NODE_USERNAME }}
          password: ${{ secrets.DB_NODE_PASSWORD }}
          envs: MESSAGE, BD_PASSWORD, BD_USER
          script: |
            echo $(echo $MESSAGE)
            
            cd /home && git clone git@github.com:KmnPetr/ZE-setting-deploy.git || true
            cd /home/ZE-setting-deploy/ && git pull || true
            
            export BD_PASSWORD=password
            export DB_USER=user
            
            docker compose -f /home/ZE-setting-deploy/postgress-docker-compose.yaml up -d
#            \
#            -e BD_PASSWORD = $(echo $BD_PASSWORD) \
#            -e BD_USER = $(echo $BD_USER)
