name: setting-ze-secret-k8s
on: workflow_dispatch

env:
  BD_PASSWORD: ${{secrets.BD_PASSWORD}}
  BD_USER: ${{secrets.BD_USER}}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up ze-secret
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_NODE_HOST }}
          username: ${{ secrets.MASTER_NODE_USERNAME }}
          password: ${{ secrets.MASTER_NODE_PASSWORD }}
          envs: BD_URL, BD_PASSWORD, BD_USER, JWT_SECRET
          script: |
            kubectl create secret generic ze-secret \
            --save-config \
            --from-literal=BD_URL=${BD_URL} \
            --from-literal=BD_PASSWORD=${BD_PASSWORD} \
            --from-literal=BD_USER=${BD_USER} \
            --from-literal=JWT_SECRET=${JWT_SECRET}